# Generated by Django 5.0.6 on 2024-06-05 23:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350)),
                ('arabicName', models.CharField(max_length=350)),
                ('visaId', models.CharField(max_length=20)),
                ('borderNumber', models.CharField(max_length=20)),
                ('nationality', models.CharField(default='Egypt', max_length=20)),
                ('arabicNationality', models.CharField(default='مصر', max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('arabicGender', models.CharField(choices=[('ذكر', 'ذكر'), ('انثى', 'انثى')], max_length=20)),
                ('serviceProvider', models.CharField(default='شركة رحلات ومنافع للسياحة', max_length=350)),
                ('serviceCenter', models.CharField(default='مركز الخدمة 239', max_length=350)),
                ('serviceCenterLocation', models.CharField(default='ام الجود', max_length=350)),
                ('serviceCenterContact', models.CharField(default='966541670802+', max_length=350)),
                ('housingMakkahLocation', models.CharField(default='اجياد البيت', max_length=350)),
                ('housingMinaLocation', models.CharField(default='-', max_length=350)),
                ('housingMadinahLocation', models.CharField(default='-', max_length=350)),
                ('housingArafatLocation', models.CharField(default='-', max_length=350)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='uploaded_images')),
                ('visaStatus', models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE')], default='ACTIVE', max_length=20, null=True)),
                ('dob', models.DateField(blank=True, default=datetime.date.today, null=True)),
            ],
        ),
    ]
