# Generated by Django 5.0.6 on 2024-06-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350)),
                ('arabicName', models.CharField(blank=True, max_length=350, null=True)),
                ('visaId', models.CharField(blank=True, max_length=20, null=True)),
                ('borderNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('nationality', models.CharField(blank=True, max_length=20, null=True)),
                ('arabicNationality', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20, null=True)),
                ('arabicGender', models.CharField(blank=True, choices=[('Male', 'ذكر'), ('Female', 'انثى')], max_length=20, null=True)),
                ('serviceProvider', models.CharField(blank=True, default='شركة رحلات ومنافع للسياحة', max_length=350, null=True)),
                ('serviceCenter', models.CharField(blank=True, default='+20 12 8956 1254', max_length=350, null=True)),
                ('serviceCenterLocation', models.CharField(blank=True, max_length=350, null=True)),
                ('serviceCenterContact', models.CharField(blank=True, max_length=350, null=True)),
                ('housingMakkahLocation', models.CharField(blank=True, default='ممكن نحط اي حاجه default', max_length=350, null=True)),
                ('housingMinaLocation', models.CharField(blank=True, default='-', max_length=350, null=True)),
                ('housingMadinahLocation', models.CharField(blank=True, default='-', max_length=350, null=True)),
                ('housingArafatLocation', models.CharField(blank=True, default='-', max_length=350, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='uploaded_images')),
                ('visaStatus', models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE')], default='ACTIVE', max_length=20, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
