# Generated by Django 5.0.6 on 2024-06-01 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_customerprofile_arabicgender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='dob',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
