# Generated by Django 5.0.6 on 2024-06-01 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_alter_customerprofile_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='arabicName',
            field=models.CharField(blank=True, default='', max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='arabicNationality',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='borderNumber',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='nationality',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='serviceCenterContact',
            field=models.CharField(blank=True, default='', max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='serviceCenterLocation',
            field=models.CharField(blank=True, default='', max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='visaId',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
