# Generated by Django 5.0.6 on 2024-06-01 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_alter_customerprofile_arabicname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='arabicName',
            field=models.CharField(default='', max_length=350),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='arabicNationality',
            field=models.CharField(blank=True, default='مصر', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='borderNumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='nationality',
            field=models.CharField(blank=True, default='Egypt', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='serviceCenter',
            field=models.CharField(blank=True, default='مركز الخدمة 239', max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='serviceCenterContact',
            field=models.CharField(blank=True, default='+20 12 8956 1254', max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='serviceCenterLocation',
            field=models.CharField(blank=True, default='ام الجود', max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='visaId',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
