# Generated by Django 5.0.6 on 2024-06-01 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_alter_customerprofile_arabicname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='arabicGender',
            field=models.CharField(choices=[('ذكر', 'ذكر'), ('انثي', 'انثى')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='arabicNationality',
            field=models.CharField(default='مصر', max_length=20),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='borderNumber',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='housingArafatLocation',
            field=models.CharField(default='-', max_length=350),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='housingMadinahLocation',
            field=models.CharField(default='-', max_length=350),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='housingMakkahLocation',
            field=models.CharField(default='ممكن نحط اي حاجه default', max_length=350),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='housingMinaLocation',
            field=models.CharField(default='-', max_length=350),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='nationality',
            field=models.CharField(default='Egypt', max_length=20),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='serviceCenter',
            field=models.CharField(default='مركز الخدمة 239', max_length=350),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='serviceCenterContact',
            field=models.CharField(default='+20 12 8956 1254', max_length=350),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='serviceCenterLocation',
            field=models.CharField(default='ام الجود', max_length=350),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='serviceProvider',
            field=models.CharField(default='شركة رحلات ومنافع للسياحة', max_length=350),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='visaId',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
